apiVersion: v1
kind: Service
metadata:
  name: web-stress-simulator
spec:
  selector:
    workload: web-stress-simulator
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer