---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-stress-simulator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-stress-simulator
  minReplicas: 1
  maxReplicas: 40
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60