apiVersion: v1
kind: Service
metadata:
  name: crashloop-app-ilb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: crashloop-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer